In [2]:
import torch

In [ ]:
[]

In [ ]:
a = torch.rand(2)

In [ ]:
a

tensor([0.6311, 0.7381])

In [ ]:
a = a.unsqueeze(0)

In [ ]:
a.size()

torch.Size([1, 2])

In [ ]:
a

tensor([[0.6311, 0.7381]])

In [ ]:
b = torch.rand(2)
b = b.unsqueeze(0)
b

tensor([[0.2663, 0.6112]])

In [ ]:
# (z, x) * (x, y) = (z, y) 
torch.matmul(a, b.transpose(0, 1))

tensor([[0.6192]])

In [4]:
text = "token0 token1 token2 token3 token4"
tokens = text.split()
set(tokens)

{'token0', 'token1', 'token2', 'token3', 'token4'}

In [5]:
vocab2id = {j:i for i, j in enumerate(list(set(tokens)))}
vocab2id

{'token4': 0, 'token2': 1, 'token3': 2, 'token1': 3, 'token0': 4}

In [6]:
[0, 0, 1, 0, 0]

[0, 0, 1, 0, 0]

In [7]:
embedding = torch.rand(5, 300)

In [8]:
# seq_len X vocab_size
# seq_len X embed_dim

In [9]:
vectors_list = []
for token in text.split():
  zero_list = [0] * len(vocab2id)
  zero_list[vocab2id[token]] = 1
  vector_index_token = torch.FloatTensor([zero_list])
  print(vector_index_token)
  token_embediing = torch.matmul(vector_index_token, embedding)
  print(token_embediing)
  break

tensor([[0., 0., 0., 0., 1.]])
tensor([[0.7482, 0.0813, 0.2078, 0.5862, 0.2929, 0.0568, 0.5187, 0.6385, 0.7633,
         0.7938, 0.1479, 0.7344, 0.0965, 0.5845, 0.9447, 0.6205, 0.9843, 0.4492,
         0.3357, 0.5231, 0.4542, 0.0104, 0.2612, 0.9847, 0.2407, 0.5858, 0.4796,
         0.3280, 0.3622, 0.8591, 0.4341, 0.1420, 0.7077, 0.2423, 0.7156, 0.5860,
         0.6475, 0.1121, 0.1043, 0.0667, 0.7676, 0.6809, 0.4258, 0.2563, 0.7089,
         0.4660, 0.4279, 0.8948, 0.8009, 0.0062, 0.2182, 0.7840, 0.0050, 0.7832,
         0.7724, 0.3490, 0.4707, 0.0266, 0.8315, 0.7134, 0.3352, 0.6606, 0.8061,
         0.3989, 0.1659, 0.6839, 0.0245, 0.1066, 0.2916, 0.9648, 0.1593, 0.7135,
         0.6433, 0.1463, 0.0353, 0.4062, 0.5863, 0.0182, 0.5398, 0.2638, 0.0490,
         0.7825, 0.4447, 0.5298, 0.3696, 0.5160, 0.7654, 0.7172, 0.9090, 0.9022,
         0.6841, 0.3234, 0.4453, 0.4696, 0.9885, 0.3150, 0.0828, 0.1081, 0.7033,
         0.5095, 0.0371, 0.9392, 0.1328, 0.8474, 0.9265, 0.7840, 0.0562, 0.124

In [10]:
from torch import nn

In [11]:
# embed_dim X len(vocab_size)

In [12]:
token_embediing.shape

torch.Size([1, 300])

In [13]:
linear_transform = torch.rand(300, 100000)

In [14]:
# token0 -> token1
w2v_logits = torch.matmul(token_embediing, linear_transform)

In [15]:
w2v_logits

tensor([[75.8004, 73.5028, 74.2753, 79.8749, 74.9903]])

In [16]:
w2v_probs = nn.functional.softmax(w2v_logits)
w2v_probs

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  """Entry point for launching an IPython kernel.


tensor([[0.0165, 0.0017, 0.0036, 0.9709, 0.0073]])

In [ ]:
token0 -- token3

[0.0165, 0.0017, 0.0036, 0.9709, 0.0073]
[0.,     0.,     0.,      1.,       0.]

In [ ]:
target = torch.LongTensor([1])

In [ ]:
loss = torch.nn.NLLLoss()

In [ ]:
w2v_probs.shape, target.shape

(torch.Size([1, 5]), torch.Size([1]))

In [ ]:
loss(w2v_probs, target)

tensor(-0.0026)

In [ ]:
# batch_size X window_size X embed_dim